CREATE TABLE public.agendamento
(
    consumidor_id bigint,
    date_time timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    procedimento_id bigint,
    CONSTRAINT agendamento_pkey PRIMARY KEY (id)
);