CREATE TABLE public.disponibilidade
(
    dia_da_semana integer,
    fim time(6) without time zone,
    inicio time(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tenant_id bigint,
    CONSTRAINT disponibilidade_pkey PRIMARY KEY (id)
);