CREATE TABLE public.procedimento
(
    habilitado boolean,
    valor numeric(38, 2),
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tenant_id bigint,
    descricao character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT procedimento_pkey PRIMARY KEY (id)
);