CREATE TABLE public.tenant
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint,
    img character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    slug character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tenant_pkey PRIMARY KEY (id),
    CONSTRAINT tenant_user_id_key UNIQUE (user_id)
);