CREATE TABLE public.users
(
    confirmacao_email boolean,
    role smallint,
    codigo_auxiliar_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    login character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_codigo_auxiliar_id_key UNIQUE (codigo_auxiliar_id),
    CONSTRAINT users_login_key UNIQUE (login)
);